name: My Action
inputs:
    fruit:
        description: Name of fruit to mask
        required: true
    secrets:
        AWS_ACCESS_KEY_ID:
            description: AWS access key
            required: true
        AWS_SECRET_ACCESS_KEY:
            description: AWS secret key
            required: true
        
runs:
  using: docker
  image: Dockerfile