name: GitHub Actions test

on: pull_request

jobs:

  build-windows:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Check choco
      run: choco list -l
    - name: Install Docker Desktop
      run: choco install -y docker-desktop
