name: GitHub Actions test

on: [push]

jobs:

  build-linux:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Look around
      run: ls
    - name: Get some info
      run: uname -a
    - name: Docker info
      run: docker info
    - name: Docker images
      run: docker images
    - name: Build Docker image
      run: docker build -t http .
    - name: Run container
      run: docker run -d -p 8080:8080 http
    - name: Test container
      run: curl http://localhost:8080

  build-windows:
 
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@master
    - name: Look around
      run: dir
    - name: Docker info
      run: docker info
    - name: Docker images
      run: docker images
    - name: Build Docker image
      run: docker build -t http .
