name: GitHub Actions test

on: pull_request

jobs:

  build-windows:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Check choco
      run: choco list -l
    - name: Build python image
      run: docker build -t python .
