name: GitHub Actions test

on:
   push:
     branches:
       - test-windows-docker

jobs:

  build-windows:
 
    runs-on: windows-2016
 
    steps:
    - uses: actions/checkout@v2
    - name: Check choco
      run: choco list -l
    - name: Build python image
      run: docker build -t python .
