name: GitHub Actions test

on:
  push:
    branches:
      - master

jobs:

  build-linux:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Look around
      run: printenv
      if: github.repository == 'StefanScherer/githubactionstest' && github.event_name == 'push'
