name: GitHub Actions test

on:
  push:
    branches:
      - master

jobs:

  build-windows:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Look around
      run: set
    - name: Check choco
      run: choco list -l
